### ISSUE TITLE
TMB.traits reshape() whitespace issue

### ISSUE THREAD

**Issue by clementviolet** [JenniNiku/gllvm#20]
Hi!

I tried to fit a 4th corner model, and I had got this weird error message. 

```
Error in `[.data.frame`(data, , varying.i) : undefined columns selected
```

In fact, it cames from the `reshape()` function.
https://github.com/JenniNiku/gllvm/blob/a2b49f0993c2bf0b6d4c2693d876a99791df5058/R/TMBtrait.R#L122

It seems that `reshape()` doesn't allow whitespace in responses names. Here a toy exemple:

```
y <- as.data.frame(matrix(rbinom(40, 1, 0.6), ncol = 4))
colnames(y) <- c("genus sp1", "genus sp2", "genus sp3", "genus sp4")
X <- data.frame(matrix(rnorm(50), ncol = 5))
traits <- data.frame(matrix(rnorm(12, 10, 8), ncol = 3))
rownames(traits) <- y
colnames(traits) <- c("A", "B", "C")
gllvm(y = y, X = X, TR = traits, family = binomial(link = "probit"), num.lv = 1) # not working

colnames(y) <- c("genus.sp1", "genus.sp2", "genus.sp3", "genus.sp4")
rownames(traits) <- y
gllvm(y = y, X = X, TR = traits, family = binomial(link = "probit"), num.lv = 1) # working
``

Maybe something could be add to the code to look after whitespace and fixe them?

**Comment by BertvanderVeen** [comment]
Good idea, I've actually encountered this myself before, though I think this is a general issue with `reshape(.)`, not isolated to `TMB.trait`, but also in `gllvm.VA`.

A potential solution, recreating the matrix from reshape(): 
`yX <- cbind(apply(replicate(ncol(y),X),2,c),time=rep(1:ncol(y),each=nrow(y)),y=c(y), id=rep(1:nrow(y),times=ncol(y)))`, where X and y need to be matrices.

**Comment by clementviolet** [comment]
I like this solution, It could deal with other special characters too (I think that `reshape()` can't handle them neither).

If we tweak a little bit your code, it could work with data frames as well and the output would still be a matrix (is it mandatory?).

```
yX <- cbind(apply(replicate(ncol(y), as.matrix(X)), 2, c), time = rep(1:ncol(y), each= nrow(y)), y = c(as.matrix(y)),  id = rep(1:nrow(y), times = ncol(y)))
```

Would you like me to create a PR?

**Comment by BertvanderVeen** [comment]
Let's not make a PR yet, as it's really up to Jenni to comment if she wants it like this, as I don't have write access to the repo. `as.matrix` works, but I think both X and y are converted to matrices in the code, which is why I didn't write it like that. Additionally, adding `as.matrix` in the wrong places has the potential to (sometimes) mess up the column names (though I think it's probably OK here).

**Comment by JenniNiku** [comment]
Ok, this needs to be addressed. However, the solution needs some thinking in order to make sure it works also in case of categorical x-variables. But I didn't find suitable solution yet.

"time" variable (named by reshape, and which is actually an index for the columns in long form) is used, at least, in the next lines after the reshape.

**Comment by clementviolet** [comment]
Maybe `dplyr` could be used instead of `reshape`? `dplyr` could be used to create the same data frame structure as reshape did.

**Comment by BertvanderVeen** [comment]
Maybe, though that would add a (not so insignificant) dependency to the package.

**Comment by JenniNiku** [comment]
This should work properly:
cbind(X[rep(1:nrow(X), times=ncol(y)),],  time = rep(1:ncol(y), each= nrow(y)), y = c(as.matrix(y)),  id = rep(1:nrow(y), times = ncol(y)))

**Comment by JenniNiku** [comment]
This is fixed now.
