### ISSUE TITLE
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) :    "FreeADFunObject" not available for .Call() for package "gllvm"

### ISSUE THREAD

**Issue by danqingxu** [JenniNiku/gllvm#22]
Hi Jenni,

I am writing a package with a function that depends on package gllvm. I updated my gllvm with the latest version on github and tried to fit a simple model using previous codes.

`fit.VA <- gllvm(Xc, family = "binomial"("probit"), method = "VA", num.lv = 1, starting.val = "random", seed = 3080)`

where Xc is a matrix with zeros and ones. I got this error message while fitting. Could you provide some insight about what this error is? I also tried with the CRAN version gllvm.

Thanks,
Danqing

**Comment by JenniNiku** [comment]
Hi! This could be due the change I have made to the code in the latest github version related to the control parameters. They are rearranged under attributes control, control.start and control.va, because there is so many control parameters that it started to look quite a mess. So current way to access to the control parameters eg. starting.val is with control.start=list(starting.val = "random"):
fit.VA <- gllvm(Xc, family = binomial("probit"), method = "VA", num.lv = 1, control.start=list(starting.val = "random"), seed = 3080)

This change is in github version only at the moment, and will be in the CRAN later.
Let me know if this will fix the problem.

Jenni
