### ISSUE TITLE
residuals.gllvm() fails when a == b in runif()

### ISSUE THREAD

**Issue by hrlai** [JenniNiku/gllvm#47]
Hi, in one of my models, I got the following error message when running `residuals(fit)` and the associated functions (e.g., `plot`):
```
Error in if (u == 1) u = 1 - 1e-16 : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In runif(n = 1, min = a, max = b) : NAs produced
```
Looking into the source code, it seems that it is due to the generation of Dunn-Symth residuals---this chunk in `residuals.gllvm`:
```
        if (object$family == "ZIP") {
            a <- pzip(as.vector(unlist(y[i, j])) - 1, mu = mu[i, j], sigma = object$params$phi[j])
            b <- pzip(as.vector(unlist(y[i, j])), mu = mu[i, j], sigma = object$params$phi[j])
            u <- runif(n = 1, min = a, max = b)
            if(u==1) u=1-1e-16
            if(u==0) u=1e-16
            ds.res[i, j] <- qnorm(u)
        }
```
In my case, `a` can be identical to `b` (both are 1 in my case), so they caused `runif(n = 1, min = a, max = b)` to create NaN: `Warning message: In runif(n = 1, min = a, max = b) : NAs produced` and then the next line to fail to assess the if condition.

**Comment by BertvanderVeen** [comment]
Thanks for posting your issue!

In my experience, this generally occurs in particularly poor fitting models. As such, I don't consider this a bug, but more a point of improvement (i.e. a more helpful error message should be given). Do you have any other indicators that the model poorly fits to your data? E.g., is there chance of overfitting due to a high degree of complexity (large number of parameters), collinearity between predictors, lack of convergence, non-singular Hessian, et cetera? 

The first thing you might try is to re-fit to model from different starting values, to see if getting to a different (hopefully better) solution solves your issue.

**Comment by hrlai** [comment]
Ah, thanks so much for the tips @BertvanderVeen . It is a microbial dataset so it's inherently high in number of parameters... 

The model convergence returned `TRUE`, but as I followed your suggestions and examine the Hessian, I got at least one singular value:
```
> solve(mod$Hess$Hess.full)
Error in solve.default(mod$Hess$Hess.full) : 
  Lapack routine dgesv: system is exactly singular: U[763,763] = 0
```
The coefs reported in the summary table all have reasonable SEs, so i suspect that this problematic coef is one of the LVs. But I don't know how to examine the estimation errors of the LVs (the helpfile of `gllvm` v1.3.1 says that `gllvm` returns an `A` object, but I couldn't find it in my model object?) 

 But you're right, this should not be considered a bug. Feel free to close this issue!
