### ISSUE TITLE
Error when installing gllvm using go

### ISSUE THREAD

**Issue by aeroned** [JenniNiku/gllvm#72]
The command `go get github.com/SRI-CSL/gllvm/shared` generates error when trying to install:

`opt/go/src/github.com/SRI-CSL/gllvm/shared/compiler.go:193:18: undefined: os.CreateTemp
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:469:21: undefined: os.MkdirTemp
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:609:21: undefined: os.MkdirTemp
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:621:18: undefined: os.CreateTemp
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:645:19: undefined: os.CreateTemp
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:780:13: undefined: os.WriteFile
opt/go/src/github.com/SRI-CSL/gllvm/shared/extractor.go:786:13: undefined: os.WriteFile
`

I have been using gllvm before and have never encountered this problem. Any possible fix?

**Comment by jarioksa** [comment]
Looks very much like a **go** issue: doesn't find operation system components `os.*` to create temporary files and directories and write files.

**Comment by JenniNiku** [comment]
Hi, and thanks for commenting Jari. @aeroned, were you able to fix the problem?  I'm not very familiar with the "go" so unfortunately I don't know how to help with that error if it is a go related issue, but otherwise I can try to check if I have made some changes to the package that could have caused problems, so do you remember when was the last time it did work?
